### PR TITLE
Solved a bug for non-conmutative operations between Number and Array.

### LINKED ISSUE #60: Incorrect results in substract operation -(A::Number, B::DArray)
When using operations like:

```julia
x = dones(10)
y = 10 - x
```

Values in `y` must be `9.0`, but it returns `-9.0`.

Similar issues happen when using other operators like `10 ./ x`.

### PR DESCRIPTION
**Pull request by JosmanPS**
Solved the problem for non-conmutative operations. Resolve #60

### CODE REVIEW

**Comment by tkelman** [comment]
Could you add a test?

**Comment by JosmanPS** [comment]
@tkelman sure.

**Comment by JosmanPS** [comment]
@tkelman Tests are ready!

**Comment by JosmanPS** [comment]
The CI fail is in `Julia:nightly`, when it's testing the `reduce` functions.
```
test DArray reduce
WARNING: Module FactCheck not defined on process 6
fatal error on 6: ERROR: UndefVarError: FactCheck not defined
```

**Comment by andreasnoack** [comment]
I'm looking into this now. It's pretty involved since it is only triggered when `inline=no`. We could probably merge your PR now but it would be good to have the tests running first.

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/issues/15766

**Comment by andreasnoack** [comment]
Tests are now passing. Thanks for fixing this bug.

**Comment by JosmanPS** [comment]
Thanks to your team. This package was very helpful for my undergraduate thesis.

**Pull request merged**
