### PR TITLE
minor cleanup

### PR DESCRIPTION
**Pull request by amitmurthy**

### CODE REVIEW

**Comment by amitmurthy** [comment]
@andreasnoack , the errors on nightly are related to a `reduced_dims` deprecation. I am going ahead and merging this. The errors on nightly can be fixed separately.

**Comment by andreasnoack** [comment]
Isn't adding fields to a type a little more than a "minor cleanup"? Could you explain?

**Comment by amitmurthy** [comment]
The container type `DArray` and the localpart were stored separately in the global registry (which is a Dict). The keys were the tuples `(id, :DARRAY)` and `(id, :LOCALPART)`. I have moved the localpart back into the container type, which visually cleans up the code and removes the need to track two separate entries in the registry. `registry[id]` now returns the darray object.

The localpart field is never serialized. On workers not participating in the distribution, the field is initialized to a 0-sized n-dimensional array of the correct type.

**Comment by andreasnoack** [comment]
Thanks for the explanation.

**Pull request merged**
