### PR TITLE
Implemented mapslices

### PR DESCRIPTION
**Pull request by amitmurthy**
This PR adds support for mapslices to DArrays.

Note that the slice dims must be completely available on the processors. There is no data movement between processors.
For example : `mapslices(sum, dones(10,10,10,10), [1,2])` requires that dimensions 1 and 2 are not distributed. Dimensions 3 and 4 can have any partition.

Tests to be added.

### CODE REVIEW

**Comment by amitmurthy** [comment]
cc: @ViralBShah , @alanedelman, @andreasnoack

**Comment by ViralBShah** [comment]
:+1:

**Comment by andreasnoack** [comment]
:+1: Just tried it and I can see an almost linear speedup with `inv`.

**Comment by amitmurthy** [comment]
Have added the same tests as from Base. Some of the tests have been commented out since DArray support for all operations is not yet complete.

I have also changed the DArray field name `pmap` to `pids` - seemed more appropriate. Can change it back if folks are using `D.pmap` in their code, though I would expect people to use `procs(D)`

**Comment by ViralBShah** [comment]
Why not call it `D.procs` then?

**Comment by alanedelman** [comment]
can we push this to multiple arguments and broadcast?
(andreas?)

**Comment by amitmurthy** [comment]
To differentiate it from procs(D). Which is the way it is meant to be
accessed anyways.

**Comment by andreasnoack** [comment]
Okay, I think I have a working serial version with arbitrary number of arguments and broadcasting now. I can open a pull request when this has been merged, but for now you can see the serial version [here](https://gist.github.com/andreasnoack/3758938f869b283b9eef)

You can do stuff like
```julia
julia> A = randn(3,2,2); B = randn(2,2,2);

julia> mapslices2(svdvals, A, B; dims = [1,2])
2x1x2 Array{Float64,3}:
[:, :, 1] =
 0.408084
 0.234047

[:, :, 2] =
  0.455504
 10.1329  

julia> mapslices2(svdvals, A, B[:,:,1]; dims = [1,2])
2x1x2 Array{Float64,3}:
[:, :, 1] =
 0.408084
 0.234047

[:, :, 2] =
 0.363922
 0.566237

julia> mapslices2(norm, A, 1; dims = [1])
1x2x2 Array{Float64,3}:
[:, :, 1] =
 1.07805  0.841196

[:, :, 2] =
 1.27439  1.28394
```
but there could be combinations that don't work. It is a bit tricky to analyze all the possible input to an arbitrary argument function with optional broadcast on all arguments.

**Comment by amitmurthy** [comment]
I guess the serial version will be added to Julia Base?

**Comment by andreasnoack** [comment]
Yes. That seems reasonable. I'll open a pull request.

**Pull request merged**
